### PR TITLE
fix(db): pass driver options to postgres-js

### LINKED ISSUE #840: NuxtHub db config ignores driver options (prepare: false) for Supabase Transaction Pooler
I am trying to connect to **Supabase** using the **Transaction Pooler (Port 6543**. While the direct connection via Port 5432 works perfectly, the pooled connection fails.  
This is likely because Supabase's transaction mode does not support prepared statements, and the prepare: false option is either not being passed correctly to the underlying driver or is being overridden by NuxtHub's internal database initialization.

### **Current Configuration**

I have attempted to configure the connection in nuxt.config.ts as follows, but without success:  

```
hub: {  
  db: {  
    dialect: "postgresql",  
    driver: "postgres-js",  
    connection: {  
      connectionString: process.env.DATABASE\_URL, // Using Port 6543  
      prepare: false, // This option seems to be ignored or not passed to the client  
    },  
  },  
},
```

.env

```
DATABASE_URL="postgresql://postgres.[PROJECT_ID]:[PASSWORD]@[REGION].pooler.supabase.com:6543/postgres"
```

### **The Problem**

- **Port 5432 (Direct):** Works as expected.  
- **Port 6543 (Transaction Pooler):** Fails to establish a stable connection or throws errors related to prepared statements.

**Silent Failure Behavior:**
Crucially, the Nuxt application does not catch or throw any errors during the database operation. On the client side, the data appears to be created successfully (as if the transaction completed), but the records are never actually persisted in the Supabase database.

**Error Logs From Supabase**

```
{
  "event_message": "prepared statement \"e3f8f0ujpgm7\" does not exist",
  "application_name": "Supavisor",
  "sql_state_code": "26000",
  "error_severity": "ERROR"
}
```

### **Environment**

- **Framework:** Nuxt ^4.3.0 
- **Module:** @nuxthub/core ^0.10.5
- **Database:** Supabase PostgreSQL  
- **Connection Mode:** Transaction Mode (Port 6543  
- **ORM:** drizzle-orm ^0.45.1

&nbsp;

### PR DESCRIPTION
**Pull request by onmax**
Closes #840

## Summary
`connection` options like `prepare: false` are silently dropped when creating postgres-js clients. Only `url` is extracted; everything else is discarded. Breaks Supabase transaction pooler (port 6543) which requires `prepare: false`.

drizzle-orm already forwards extra connection fields to `postgres()` via `const { url, ...config } = connection; postgres(url, config)`. For the simple case (no replicas), we now let drizzle handle client creation. For replicas/lazy init, we strip only `url` and spread the rest.

## StackBlitz

| | Link | Expected |
|---|---|---|
| Bug | [nuxthub-840](https://stackblitz.com/github/onmax/repros/tree/repro/nuxthub-840/nuxthub-840?startScript=build) | `prepare` missing from postgres() call |
| Fix | [nuxthub-840-fix](https://stackblitz.com/github/onmax/repros/tree/repro/nuxthub-840/nuxthub-840-fix?startScript=build) | `prepare: false` present |

## CLI Reproduction

```bash
git clone --depth 1 --filter=blob:none --sparse --branch repro/nuxthub-840 https://github.com/onmax/repros.git
cd repros && git sparse-checkout set nuxthub-840
cd nuxthub-840 && pnpm i && pnpm build
# Check node_modules/@nuxthub/db/db.mjs — prepare is missing
```

## Verify fix

```bash
git sparse-checkout add nuxthub-840-fix
cd ../nuxthub-840-fix && pnpm i && pnpm build
# Check node_modules/@nuxthub/db/db.mjs — prepare: false is present
```

The `-fix` folder uses [pnpm patch](https://pnpm.io/cli/patch) to apply the fix locally.

### CODE REVIEW

**Review by onmax — COMMENTED** [review]
NuxtHub-specifci fields (hyperdriveId, accountId, etc.) leak into `postgresOpts`, which is benign but could be cleaner

File: src/db/lib/client.ts [hunk 1]
```diff
@@ -45,14 +43,9 @@ export async function createDrizzleClient(config: ResolvedDatabaseConfig, hubDir
...
   } else if (driver === 'postgres-js') {
-    const clientPkg = 'postgres'
-    const { default: postgres } = await import(clientPkg)
-    client = postgres(connection.url, {
-      onnotice: () => {}
-    })
     pkg = 'drizzle-orm/postgres-js'
     const { drizzle } = await import(pkg)
-    return drizzle({ client, casing })
+    return drizzle({ connection: { ...connection, onnotice: () => {} }, casing })
```
Comment (atinux) [inline src/db/lib/client.ts]: `onnotice` cannot be given to the `drizzle` client @onmax 

Where did you see this was possible?

Comment (onmax) [reply src/db/lib/client.ts]: Passing `onnotice` via connection is supported by drizzle `postgres-js` driver (it proxies the options to postgres-js), right?
