### PR TITLE
fix(db): update `neon-http` connection string format in setup.ts

### LINKED ISSUE #744: Inconsistent config of database setup connection url
**Describe the bug**
In the docs there is the following seciont of "advanced configuration" that shows the option to include a custom connection string

```ts
export default defineNuxtConfig({
  hub: {
    db: {
      dialect: 'postgresql',
      driver: 'postgres-js', // Optional: explicitly choose driver
      connection: {
        connectionString: process.env.DATABASE_URL
      }
    }
  }
})
```
But `connection.connectionString`  is only used for neon. Everywhere else, db/setup.ts looks for `connection.url`

connection.url:
https://github.com/nuxt-hub/core/blob/7d6122b2fd57f401d54fbfe0b7ec654754509b34/src/db/setup.ts#L69-L75

https://github.com/nuxt-hub/core/blob/7d6122b2fd57f401d54fbfe0b7ec654754509b34/src/db/setup.ts#L317-L319

connection.connectionString for neon:
https://github.com/nuxt-hub/core/blob/7d6122b2fd57f401d54fbfe0b7ec654754509b34/src/db/setup.ts#L329

So if the db config is set as the example in the docs, the setup defaults to an empty string that throws an authentication error. And if driver is not set, it defaults to pglite.

But if `DATABASE_URL` is set everything works fine. As its said in the docs:
```
NuxtHub automatically detects your database connection using environment variables:
Uses PGlite (embedded PostgreSQL) if no environment variables are set.
Uses postgres-js driver if you set DATABASE_URL, POSTGRES_URL, or POSTGRESQL_URL environment variable.
Use neon-http driver with @neondatabase/serverless for [Neon](https://neon.com/) serverless PostgreSQL.
```
So setting `connectionString` with  `DATABASE_URL` might give the illusion that `connectionString` is being read, but instead, is being read directly from the env variables. 

I just filed this issue to document the behavior.

### PR DESCRIPTION
**Pull request by adamkasper**
resolves #744

### CODE REVIEW

File: src/db/setup.ts [hunk 1]
```diff
@@ -326,7 +326,7 @@ export { db, schema }
 import { drizzle } from 'drizzle-orm/neon-http'
 import * as schema from './db/schema.mjs'
 
-const sql = neon(${connection.connectionString})
+const sql = neon(${JSON.stringify(connection.url)})
```
Comment (atinux) [inline src/db/setup.ts]:
```suggestion
const sql = neon('${connection.url}')
```
