### PR TITLE
fix: normalize path for windows

### LINKED ISSUE #316: throwIfUnsupportedURLScheme
**Describe the bug**
@nuxthub/core 0.7.27 is throwing:
```
ERROR  Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'e:'                              11:14:59 PM  

  at throwIfUnsupportedURLScheme (node:internal/modules/esm/load:249:11)
  at defaultLoad (node:internal/modules/esm/load:130:3)
  at ModuleLoader.load (node:internal/modules/esm/loader:555:13)
  at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:434:56)
  at new ModuleJob (node:internal/modules/esm/module_job:71:27)
  at #createModuleJob (node:internal/modules/esm/loader:447:17)
  at ModuleLoader.getJobFromResolveResult (node:internal/modules/esm/loader:259:34)
  at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:17)
  at async ModuleLoader.import (node:internal/modules/esm/loader:472:23)
```

**Steps to reproduce**
This is hapening on windows 11
Node 20.18.0
Pnpm 9.12.0

**Expected behavior**
Reverted to 0.7.26
* no error 😎

### PR DESCRIPTION
**Pull request by atinux**
resolves #316

### CODE REVIEW

File: src/features.ts [hunk 1]
```diff
@@ -1,4 +1,6 @@
 import { execSync } from 'node:child_process'
+import { pathToFileURL } from 'node:url'
```
Comment (pi0) [inline src/features.ts:2]: Tip: if you use `pathToFileURL` from `mlly`, it handles windows situation and returns string

Comment (atinux) [reply src/features.ts:2]: I see, was updating based on https://github.com/unjs/nitro/pull/732/files

Comment (atinux) [reply src/features.ts]: Updated with https://github.com/nuxt-hub/core/pull/317/commits/49f67b5b3965382755f7e74ab9fa5157d044b82f
