### PR TITLE
fix(db): resolve Nuxt aliases in schema bundling

### LINKED ISSUE #800: 🐞 NuxtHub 0.10.5: server/db/schema imports break when using #shared alias
## 🐛 Description
After upgrading from `@nuxthub/core@0.10.4` to `0.10.5`, imports inside
`server/db/schema` stopped working when using the `#shared` Nuxt alias.

## ✅ What worked before (0.10.4)
Imports like the following worked correctly:

```ts
import { something } from '#shared/utils/accounts'
```

## ❌ What happens in 0.10.5
At runtime, Node throws the following error:

Package import specifier "#shared/utils/accounts" is not defined in package
.../node_modules/@nuxthub/db/package.json

🔍 Observation

This appears to be a behavior change compared to 0.10.4.
Schema imports now rely on Node-only module resolution.

💡 Expected behavior / suggestion

Either:

- 📘 Document clearly that server/db/schema must not rely on the #shared
alias and should use Node-resolvable imports, or

- 🔧 Preserve #shared alias resolution for schema imports if possible.

Happy to adjust code — just wanted to report this since it wasn’t obvious
during the upgrade 🙏

### PR DESCRIPTION
**Pull request by onmax**
Closes #800

## Summary
Schema files bundled via tsdown didn't resolve Nuxt aliases (`#shared`, `~`, `@`). Now passes `nuxt.options.alias` to `buildDatabaseSchema()` so tsdown can resolve them.

## StackBlitz

| | Link | Expected |
|---|---|---|
| Bug | [nuxthub-800](https://stackblitz.com/github/onmax/repros/tree/repro/nuxthub-800/nuxthub-800?startScript=build) | ❌ Build fails |
| Fix | [nuxthub-800-fixed](https://stackblitz.com/github/onmax/repros/tree/repro/nuxthub-800/nuxthub-800-fixed?startScript=build) | ✅ Build succeeds |

## CLI Reproduction

```bash
git clone --depth 1 --filter=blob:none --sparse --branch repro/nuxthub-800 https://github.com/onmax/repros.git
cd repros && git sparse-checkout set nuxthub-800
cd nuxthub-800 && pnpm i && pnpm build
```

## Verify fix

```bash
git sparse-checkout add nuxthub-800-fixed
cd ../nuxthub-800-fixed && pnpm i && pnpm build
```

The `-fixed` folder uses [pnpm patch](https://pnpm.io/cli/patch) to apply the fix locally.

## Related
- https://github.com/nuxt-hub/core/issues/800

### CODE REVIEW

**Review by atinux — APPROVED** [review]

**Comment by atinux** [comment]
I'm good with this, but the CLI commands might keep failing as `buildDatabaseSchema` is called in `generate` and `squash` commands ⚠️

**Comment by onmax** [comment]
@atinux Added CLI support - generate and squash commands now read aliases from `.nuxt/tsconfig.json`

File: cli/commands/db/generate.mjs [hunk 1]
```diff
@@ -1,9 +1,25 @@
+import { readFile } from 'node:fs/promises'
 import { defineCommand } from 'citty'
 import { consola } from 'consola'
 import { execa } from 'execa'
 import { join, resolve } from 'pathe'
 import { buildDatabaseSchema } from '@nuxthub/core/db'
 
+async function getTsconfigAliases(cwd) {
```
Comment (baianux) [inline cli/commands/db/generate.mjs]: Is it better to `getTsconfigAliases` be inside `utils/db.mjs` instead of duplicate it?

Comment (onmax) [reply cli/commands/db/generate.mjs]: Done in b588418. Thanks for the suggestion @baianux!

**Review by atinux — APPROVED** [review]
