### PR TITLE
fix(build): merge nitro generated env to root in wrangler.json 

### LINKED ISSUE #704: Migration doesn't seems to work
I tired the migration for 2 projects, followed the steps, but I always getting following error:

 ⛅️ wrangler 4.53.0
───────────────────
Using redirected Wrangler configuration.
 - Configuration being used: "server/wrangler.json"
 - Original user's configuration: "../wrangler.jsonc"
 - Deploy configuration file: "../.wrangler/deploy/config.json"

✘ [ERROR] Processing server/wrangler.json configuration:

    - Redirected configurations cannot include environments but the following have been found:
        - preview
  
  
      Such configurations are generated by tools, meaning that one of the tools
      your application is using is generating the incorrect configuration.
      Report this issue to the tool's author so that this can be fixed there.

Update your nuxt.config.ts to include the following configuration:

```
export default defineNuxtConfig({
  compatibilityDate: "2025-12-11",
  nitro: {
    preset: "cloudflare_module",
    cloudflare: {
      deployConfig: true,
      nodeCompat: true
    }
  }
})
```

Create a wrangler.jsonc file in the root of your project with the following configuration:

```
{
  "$schema": "node_modules/wrangler/config-schema.json",
  "name": "<NAME>",
  "main": "./.output/server/index.mjs",
  "compatibility_date": "2025-12-11",
  "assets": {
    "directory": "./.output/public/",
    "binding": "ASSETS"
  },
  "observability": {
    "enabled": true
  },
  "env": {
    "preview": {}
  }
}
```

How can I fix this?

Kind regards.

### PR DESCRIPTION
**Pull request by RihanArfan**
Closes #704

https://github.com/cloudflare/workers-sdk/pull/8596

### CODE REVIEW

File: src/module.ts [hunk 1]
```diff
@@ -100,6 +101,8 @@ export default defineNuxtModule<ModuleOptions>({
           compatibility_flags: ['nodejs_compat']
         })
       }
```
Comment (atinux) [inline src/module.ts]: I would also move this code within the `setupCloudflare()` function.

Are you happy to move `src/cloudflare.ts` to `src/hosting/cloudflare.ts`
